// The house draws itself on like a pencil sketch — every stroked line animates
// via stroke-dashoffset, driven by a <style> block baked into the SVG itself
// (generated by scripts/animate-casa.mjs from the flat Figma export).
//
// That only plays when the SVG document actually loads as its own browsing
// context, which rules out a plain `<img src>`: browsers freeze CSS (and SMIL)
// animations inside an SVG loaded that way, showing just its first frame
// forever. The fix isn't to inline the file's ~850KB of markup into every
// HTML response either — that used to happen here and nearly doubled the
// page's transfer size on every single request. `<object>` gets both
// properties at once: the embedded SVG document runs its own CSS animations
// exactly like an inlined one would, while the file stays a normal, separate,
// long-term-cacheable request (see the `/assets/:path*` immutable header in
// next.config.ts) that downloads in parallel with the rest of the page
// instead of bloating it.
export function HeroCasa() {
  return (
    <object
      className="imob-hero__casa"
      type="image/svg+xml"
      data="/assets/imob/hero-casa.svg"
      aria-hidden="true"
    />
  );
}
