import { readFileSync } from 'node:fs';
import { join } from 'node:path';

// The house draws itself on like a pencil sketch — every stroked line animates
// via stroke-dashoffset, driven by a <style> block baked into the SVG itself
// (generated by scripts/animate-casa.mjs from the flat Figma export).
//
// That only plays when the SVG is part of the live DOM: browsers freeze CSS
// (and SMIL) animations inside an SVG loaded through a plain <img src>, showing
// just its first frame forever. So instead of `<img src="/assets/imob/hero-casa.svg">`,
// this Server Component reads the file straight off disk at render time and
// inlines its markup — same asset, same single source of truth for
// `public/assets/imob/hero-casa.svg`, just delivered as real DOM instead of an
// opaque image resource. It has no props and no client logic, so — unlike
// Hero.tsx, which needs `useI18n` — it stays a plain server component and never
// ships this markup as client JS; Hero only receives it as pre-rendered children.
const CASA_SVG = readFileSync(
  join(process.cwd(), 'public/assets/imob/hero-casa.svg'),
  'utf8',
);

export function HeroCasa() {
  return (
    <div className="imob-hero__casa" aria-hidden="true" dangerouslySetInnerHTML={{ __html: CASA_SVG }} />
  );
}
